# -*- coding: utf-8 -*-
"""Двухканальный ЭЭГ анализ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18z0fboEe7uEPlhywEvK_0-IajutpulA9

# Загрузка библиотек для анализа
"""

pip install mne

import numpy as np
import pandas
import mne
import matplotlib.pyplot as plt

"""# Вставьте название файлов"""

filename_EC = 'm25abcd_Seance2_1_Тест_глаза_закрыты.edf'
filename_EO = 'm25abcd_Seance2_2_Тест_глаза_открыты.edf'

"""# Чтение, объединение и фильтрация файлов"""

end_index = filename_EC.find('_1_Тест')

if end_index != -1:
    name_export_file = filename_EC[:end_index]
else:
    name_export_file = filename_EC

"""добавить возможность просматривать ээг чтобы проставлять метки произвольно"""

#название файла
raw_ec = mne.io.read_raw_edf(filename_EC, preload=True)
print(len(raw_ec))

raw_ec.plot(scalings={'eeg': 100}, start=10, duration=5)

#название файла
raw_EO = mne.io.read_raw_edf(filename_EO, preload=True)
print(len(raw_EO))

raw_EO.plot(scalings={'eeg': 100}, start=10, duration=5)

"""убрать артефактные участки перед анализом"""

channels = raw_EO.ch_names
print(channels)

# Получение списка каналов
channels = raw_ec.ch_names
print(channels)

# Создание списка каналов, которые вы хотите оставить
channels_to_keep = ['ECG1', 'EEG1', 'EEG2', 'EMG1']

# Выбор только необходимых каналов
raw_ec.pick_channels(channels_to_keep)
raw_EO.pick_channels(channels_to_keep)
raw_ec.plot(scalings={'eeg': 100}, duration=4)

events_ec = np.array([[10000, 0, 1]])
event_dict = {'EC': 1}
epochs_ec = mne.Epochs(raw_ec, events_ec, event_id=event_dict, tmin=0.0, tmax=8.0, baseline=None, preload=True)

# Визуализация эпох
epochs_ec.plot(scalings={'eeg': 100})

events_eo = np.array([[100, 0, 1]])
# Изменение идентификаторов
events_eo[events_eo[:, 2] == 1, 2] = 2  # Изменение всех событий с ID '2' на '5'
event_dict_eo = {'EO': 2}
epochs_eo = mne.Epochs(raw_EO, events_eo, event_id=event_dict_eo, tmin=0.0, tmax=8.0, baseline=None, preload=True)

# Визуализация эпох
epochs_eo.plot(scalings={'eeg': 100})

# Проверка частоты дискретизации для каждого объекта Epochs
sfreq_ec = epochs_ec.info['sfreq']
sfreq_eo = epochs_eo.info['sfreq']

print(f'Частота дискретизации в epochs_ec: {sfreq_ec}')
print(f'Частота дискретизации в epochs_eo: {sfreq_eo}')

# Если частоты различаются, нужно изменить одну из Epochs
if sfreq_ec != sfreq_eo:
    # Пример: приведем epochs_eo к частоте epochs_ec
    if sfreq_ec < sfreq_eo:
        epochs_eo = epochs_eo.resample(sfreq_ec)  # Ресемплинг epochs_eo
    else:
        epochs_ec = epochs_ec.resample(sfreq_eo)  # Ресемплинг epochs_ec

# Теперь можно производить обрезку
tmin = 0  # начало извлечения
tmax = 8  # конец извлечения

# Обрезааем обе выборки
epochs_ec_selected = epochs_ec.copy().crop(tmin=tmin, tmax=tmax)
epochs_eo_selected = epochs_eo.copy().crop(tmin=tmin, tmax=tmax)

# Объединяем обе выборки
combined_epochs = mne.concatenate_epochs([epochs_ec_selected, epochs_eo_selected])

# Проверка формы объединенного объекта
print('Форма объединённых эпох:', combined_epochs.get_data().shape)

# Фильтрация данных для извлечения альфа-диапазона (3-20 Гц)
raw_ec.filter(3,20)
raw_EO.filter(3,20)

epochs_info = raw_ec.info
epochs_ec = mne.EpochsArray(epochs_ec, info=epochs_info)
epochs_ec.plot(scalings={'eeg': 100})

combined_epochs.plot(scalings={'eeg': 80})

"""вручную вырезать артефакты (амплитудные можно через компоненты вырезать)

# ICA анализ
"""

# вместо ica взять диапазон где супрессировалась и фильтровать окно 250 мс
def eeg_ica(eeg, ic_number = None):
    ica = mne.preprocessing.ICA(n_components=ic_number,
                                noise_cov=None,
                                random_state=42,
                                method='infomax',
                                fit_params=dict(extended=True))
    ica.fit(eeg, picks=['eeg'])
    ica.apply(eeg)
    return ica

ica = eeg_ica(combined_epochs, ic_number = 4)
ica.plot_sources(combined_epochs, start=0, stop=3, show_scrollbars=True)

epochs_ica = ica.apply(combined_epochs)

# 1 and 3

"""*Впишите в ячейке ниже каналы для удаления*"""

# Вы хотите удалить компоненты с индексами 1 и 3
ica.exclude = [0,3]

# Применение исправлений к исходным эпохам
epochs_corrected = ica.apply(combined_epochs)

"""# Построение графиков после ica"""

ica.plot_sources(combined_epochs, start=0, stop=10, show_scrollbars=True)

epochs_corrected.plot(scalings={'eeg': 100})

"""# Fast Furie Transformation

"""

#Эти параметры можно варьировать для фильтрации по частоте альфа
max_freq = 15
min_freq = 7

from mne.time_frequency import tfr_morlet, tfr_multitaper
freqs = np.linspace(min_freq, max_freq, num=77)

n_cycles = freqs / 2.
power, itc = tfr_morlet(epochs_ica, freqs=freqs, n_cycles=n_cycles, use_fft=True,
                        return_itc=True, decim=3, n_jobs=1)
tfr_morlet(epochs_ica, freqs=freqs, n_cycles=n_cycles, use_fft=True,
                        return_itc=True, decim=3, n_jobs=1)

# исползоть 0.5 гц
spec_ec = epochs_corrected['EC'].compute_psd(method='welch', fmin=min_freq, fmax=max_freq,
                                                n_fft=1000, n_overlap=500)
spec_eo = epochs_corrected['EO'].compute_psd(method='welch', fmin=min_freq, fmax=max_freq,
                                             n_fft=1000, n_overlap=500)

ec = spec_ec.to_data_frame()
ec['EEG'] = (ec['EEG1']+ ec['EEG2'])/200

eo = spec_eo.to_data_frame()
eo['EEG'] = (eo['EEG1']+ eo['EEG2'])/200

#построить усредненный о1 и о2
plt.plot(ec['freq'], ec['EEG'], label = 'ЗГ')
plt.plot(eo['freq'],eo['EEG'], label = 'ОГ')
#plt.plot(ec['freq'],eo['EEG1'] - ec['EEG1'], label = 'ОГ- ЗГ')
plt.legend()

plt.title('')
#plt.ylim(0, 5*10**-10)
plt.xlabel('Hz')
plt.ylabel('μV$^2$ $/{Hz}$ ')
ec.to_excel('EC.xlsx')
# y - мощность мквольт^2
# x - Hz (/8)

"""# График мощности (Power Plot)

**Что показывает:** График мощности визуализирует распределение мощности ЭЭГ-сигнала в зависимости от времени и частоты. Он демонстрирует, какие частоты активны в определенные моменты времени и с какой интенсивностью.

**Параметры**:

**Канал (например, 'EEG1'):** Выбор канала для анализа, который будет отображен.

**Базовая линия:** Указывает временной интервал (например, -0.7 до 0 секунд), который используется для нормализации данных.

**Логарифмическое отношение:** Отображает мощность в виде логарифмического отношения к базовой линии.

**Цветовая карта ('jet'):** Выбор цветовой схемы для визуализации мощности.


***График ITC (Inter-Trial Coherence Plot)***
**Что показывает:** График интер-channel coherence (ITC) измеряет синхронность ЭЭГ-сигналов между различными попытками (триIALs). Он показывает, насколько консистентно сигналы в разных пробах в ответ на одно и то же событие.

**Параметры**:

**Канал (например, 'EEG1'):** Выбор канала для анализа.

**Режим ('mean'):** Отображает среднее значение ITC по всем испытаниям.

**Временной интервал:** Например, от -0.7 до 8.0 секунд, что охватывает время до и после события.

**Цветовая карта ('Reds')**: Выбор цветовой схемы для визуализации ITC.
"""

from mne.time_frequency import tfr_morlet, tfr_multitaper #нужно в ответ на открывание глаз
# Выбор канала для анализа (например, Fz)
#freqs = np.linspace(1, 30, num=8)
freqs = np.logspace(*np.log10([1, 30]), num=29)
n_cycles = freqs / 2.

power, itc = tfr_morlet(epochs_ica, freqs=freqs, n_cycles=n_cycles, use_fft=True, return_itc=True, decim=3, n_jobs=1)
#power, itc = tfr_multitaper(epochs_ica, freqs=freqs, n_cycles=n_cycles, time_bandwidth=2, return_itc=True)

power.plot('EEG1', baseline=(0, 0), mode='logratio', tmin=0, tmax=8, cmap='jet') #  vmin=-0.001, vmax=0.001,
itc.plot('EEG1', mode='mean', tmin=-0, tmax=8.0, cmap='Reds') # baseline=(-0.7, -0.2)
1

"""# Рассчет параметров и сохранение в .xslx файл

"""

IAPF_EEG = ec.loc[(ec['freq'] >= min_freq) & (ec['freq'] <= max_freq), 'EEG'].max()
IAPF_index = ec.loc[(ec['freq'] >= min_freq) & (ec['freq'] <= max_freq) & (ec['EEG'] == IAPF_EEG)].index[0]
IAPF = ec.at[IAPF_index, 'freq']
IAPF

from re import ASCII
import math
# Рассчитываем порог 20%
threshold = 0.2 # Порог 20%

# Находим строки слева и справа от максимального значения, где разница между 'ec' и 'eo' не превышает 20%
left_row = None
right_row = None
for i in range(IAPF_index-1, -1, -1):
    if abs(ec.at[i, 'EEG'] - eo.at[i, 'EEG']) / ec.at[i, 'EEG'] < threshold:
        left_row = ec.iloc[i]
        TF_index = i
        break

last_value = -1

min_ratio=10
for i in range(IAPF_index, len(ec)):
    ratio = abs(ec.at[i, 'EEG'] - eo.at[i, 'EEG']) / ec.at[i, 'EEG']
    if ratio < min_ratio:
        min_ratio = ratio
        last_value = i
        right_row = ec.iloc[last_value]
        BF_index = i
    elif last_value != -1:
        right_row = ec.iloc[last_value]
        BF_index = i
        break

#print("The row to the left of the maximum value in 'ec' where the difference is within 20%:", left_row)
#print("The row to the right of the maximum value in 'ec' where the difference is within 20%:", right_row)
TF = left_row['freq']
BF = right_row['freq']
ABW = abs(TF-BF)
ABW_alpha1 = IAPF-TF
ABW_alpha2 = abs(IAPF-BF)
PSD_alpha1_ec = np.trapz(ec['EEG'].iloc[TF_index:IAPF_index+1],
                            x=ec['freq'].iloc[TF_index:IAPF_index+1])
PSD_alpha2_ec = np.trapz(ec['EEG'].iloc[IAPF_index :BF_index+1],
                            x=ec['freq'].iloc[IAPF_index:BF_index+1])
PSD_alpha1_eo = np.trapz(eo['EEG'].iloc[TF_index:IAPF_index+1],
                            x=eo['freq'].iloc[TF_index:IAPF_index+1])
PSD_alpha2_eo = np.trapz(eo['EEG'].iloc[IAPF_index :BF_index+1],
                            x=eo['freq'].iloc[IAPF_index:BF_index+1])
a2a_ec = PSD_alpha1_ec/PSD_alpha2_ec
a2a_eo = PSD_alpha1_eo/PSD_alpha2_eo


AA1S = math.log((PSD_alpha1_ec - PSD_alpha1_eo)/PSD_alpha1_ec *100 )
AA2S = math.log((PSD_alpha2_ec - PSD_alpha2_eo)/PSD_alpha2_ec *100 )
ASIAP = math.log((ec.at[IAPF_index, 'EEG']  - eo.at[IAPF_index, 'EEG'])/ec.at[IAPF_index, 'EEG'] *100)
print('TF:', TF)
print('BF:', BF)
print('ABW:', ABW)
print('ABW_alpha1:', ABW_alpha1)
print('ABW_alpha2:', ABW_alpha2)
print('PSD_alpha1_ec:', PSD_alpha1_ec)
print('PSD_alpha2_ec:', PSD_alpha2_ec)
print('PSD_alpha1_eo:', PSD_alpha1_eo)
print('PSD_alpha2_eo:', PSD_alpha2_eo)
print('AA1S', AA1S)
print('AA2S', AA2S)
print('IAPF:', IAPF)
print('ASIAPF', ASIAP)
print('a2a_ec', a2a_ec)
print('a2a_eo', a2a_eo)
#PSD - мощность
#(PSD_ec-PSD_eo)/PSD_ec

# в таблицу сохраняем
import pandas as pd

# Create a dictionary with the computed values
data = {
    'IAPF': [IAPF],
    'TF': [TF],
    'BF': [BF],
    'ABW': [ABW],
    'ABW_alpha1': [ABW_alpha1],
    'ABW_alpha2': [ABW_alpha2],
    'PSD_alpha1_ec': [PSD_alpha1_ec],
    'PSD_alpha2_ec': [PSD_alpha2_ec],
    'PSD_alpha1_eo': [PSD_alpha1_eo],
    'PSD_alpha2_eo': [PSD_alpha2_eo],
    'AA1S': [AA1S],
    'AA2S': [AA2S],
    'ASIAPF': [ASIAP],
    'a1_to_a2_ec': [a2a_ec],
    'a1_to_a2_eo': [a2a_eo]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Save the DataFrame to an Excel file
df.to_excel(f'result_{name_export_file}_EEG analysis.xlsx', index=False)

